### ISSUE TITLE
树莓派运行错误

### ISSUE THREAD

**Issue by Xu77** [ChenWenBrian/AliDDNS#1]
Nslookup IP:  223.6.6.6#53
./aliddns.sh: 30: read: Illegal option -n
./aliddns.sh: 30: read: Illegal option -n
Aliyun   IP:
root@raspberrypi:~#

**Comment by ChenWenBrian** [comment]
提供下系统与版本信息，另外也可以把详细的调试信息输出看看`sh -x ./aliddns.sh`
