### ISSUE TITLE
只能改本地Host? 这不是改alidns的解析的？

### ISSUE THREAD

**Issue by Uzibird** [ChenWenBrian/AliDDNS#2]

**Comment by ChenWenBrian** [comment]
这是一个客户端的本地查询脚本，目的是解决动态IP切换的时候，DNS缓存问题。

如要修改阿里的DNS解析记录，有很多同类脚本

**Comment by Uzibird** [comment]
> 这是一个客户端的本地查询脚本，目的是解决动态IP切换的时候，DNS缓存问题。
> 
> 如要修改阿里的DNS解析记录，有很多同类脚本
好吧，打扰了。
